/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fi.soveltia.liferay.gsearch.click.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Clicks service. Represents a row in the &quot;GSearchClickTracking_Clicks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>fi.soveltia.liferay.gsearch.click.tracking.model.impl.ClicksModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>fi.soveltia.liferay.gsearch.click.tracking.model.impl.ClicksImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Clicks
 * @generated
 */
@ProviderType
public interface ClicksModel
	extends BaseModel<Clicks>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clicks model instance should use the {@link Clicks} interface instead.
	 */

	/**
	 * Returns the primary key of this clicks.
	 *
	 * @return the primary key of this clicks
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clicks.
	 *
	 * @param primaryKey the primary key of this clicks
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this clicks.
	 *
	 * @return the uuid of this clicks
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this clicks.
	 *
	 * @param uuid the uuid of this clicks
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the click ID of this clicks.
	 *
	 * @return the click ID of this clicks
	 */
	public long getClickId();

	/**
	 * Sets the click ID of this clicks.
	 *
	 * @param clickId the click ID of this clicks
	 */
	public void setClickId(long clickId);

	/**
	 * Returns the group ID of this clicks.
	 *
	 * @return the group ID of this clicks
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this clicks.
	 *
	 * @param groupId the group ID of this clicks
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this clicks.
	 *
	 * @return the company ID of this clicks
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this clicks.
	 *
	 * @param companyId the company ID of this clicks
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this clicks.
	 *
	 * @return the create date of this clicks
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this clicks.
	 *
	 * @param createDate the create date of this clicks
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this clicks.
	 *
	 * @return the modified date of this clicks
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this clicks.
	 *
	 * @param modifiedDate the modified date of this clicks
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the keywords of this clicks.
	 *
	 * @return the keywords of this clicks
	 */
	@AutoEscape
	public String getKeywords();

	/**
	 * Sets the keywords of this clicks.
	 *
	 * @param keywords the keywords of this clicks
	 */
	public void setKeywords(String keywords);

	/**
	 * Returns the entry class pk of this clicks.
	 *
	 * @return the entry class pk of this clicks
	 */
	public long getEntryClassPK();

	/**
	 * Sets the entry class pk of this clicks.
	 *
	 * @param entryClassPK the entry class pk of this clicks
	 */
	public void setEntryClassPK(long entryClassPK);

	/**
	 * Returns the click count of this clicks.
	 *
	 * @return the click count of this clicks
	 */
	public int getClickCount();

	/**
	 * Sets the click count of this clicks.
	 *
	 * @param clickCount the click count of this clicks
	 */
	public void setClickCount(int clickCount);

}